/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as ClientRouteImport } from './routes/client'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoachProgramsRouteImport } from './routes/coach.programs'
import { Route as CoachLibraryRouteImport } from './routes/coach.library'
import { Route as CoachExercisesRouteImport } from './routes/coach.exercises'
import { Route as CoachDashboardRouteImport } from './routes/coach.dashboard'
import { Route as ClientWorkoutHistoryRouteImport } from './routes/client.workout-history'
import { Route as ClientDashboardRouteImport } from './routes/client.dashboard'
import { Route as CoachProgramsIndexRouteImport } from './routes/coach.programs.index'
import { Route as CoachLibraryIndexRouteImport } from './routes/coach.library.index'
import { Route as CoachProgramsProgramIdRouteImport } from './routes/coach.programs.$programId'
import { Route as CoachLibraryWorkoutsRouteImport } from './routes/coach.library.workouts'
import { Route as CoachLibraryExercisesRouteImport } from './routes/coach.library.exercises'
import { Route as CoachClientsClientIdRouteImport } from './routes/coach.clients.$clientId'
import { Route as CoachProgramsProgramIdIndexRouteImport } from './routes/coach.programs.$programId.index'
import { Route as CoachLibraryWorkoutsIndexRouteImport } from './routes/coach.library.workouts.index'
import { Route as CoachLibraryWorkoutsWorkoutIdRouteImport } from './routes/coach.library.workouts.$workoutId'
import { Route as CoachLibraryWorkoutsWorkoutIdIndexRouteImport } from './routes/coach.library.workouts.$workoutId.index'
import { Route as CoachProgramsProgramIdWorkoutsWorkoutIdRouteImport } from './routes/coach.programs.$programId.workouts.$workoutId'
import { Route as CoachLibraryWorkoutsWorkoutIdPreviewRouteImport } from './routes/coach.library.workouts.$workoutId.preview'
import { Route as ClientProgramsProgramIdWorkoutsWorkoutIdRouteImport } from './routes/client.programs.$programId.workouts.$workoutId'
import { Route as CoachProgramsProgramIdWorkoutsWorkoutIdIndexRouteImport } from './routes/coach.programs.$programId.workouts.$workoutId.index'
import { Route as CoachProgramsProgramIdWorkoutsWorkoutIdPreviewRouteImport } from './routes/coach.programs.$programId.workouts.$workoutId.preview'

const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachProgramsRoute = CoachProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => CoachRoute,
} as any)
const CoachLibraryRoute = CoachLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => CoachRoute,
} as any)
const CoachExercisesRoute = CoachExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => CoachRoute,
} as any)
const CoachDashboardRoute = CoachDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CoachRoute,
} as any)
const ClientWorkoutHistoryRoute = ClientWorkoutHistoryRouteImport.update({
  id: '/workout-history',
  path: '/workout-history',
  getParentRoute: () => ClientRoute,
} as any)
const ClientDashboardRoute = ClientDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ClientRoute,
} as any)
const CoachProgramsIndexRoute = CoachProgramsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoachProgramsRoute,
} as any)
const CoachLibraryIndexRoute = CoachLibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoachLibraryRoute,
} as any)
const CoachProgramsProgramIdRoute = CoachProgramsProgramIdRouteImport.update({
  id: '/$programId',
  path: '/$programId',
  getParentRoute: () => CoachProgramsRoute,
} as any)
const CoachLibraryWorkoutsRoute = CoachLibraryWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => CoachLibraryRoute,
} as any)
const CoachLibraryExercisesRoute = CoachLibraryExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => CoachLibraryRoute,
} as any)
const CoachClientsClientIdRoute = CoachClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => CoachRoute,
} as any)
const CoachProgramsProgramIdIndexRoute =
  CoachProgramsProgramIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CoachProgramsProgramIdRoute,
  } as any)
const CoachLibraryWorkoutsIndexRoute =
  CoachLibraryWorkoutsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CoachLibraryWorkoutsRoute,
  } as any)
const CoachLibraryWorkoutsWorkoutIdRoute =
  CoachLibraryWorkoutsWorkoutIdRouteImport.update({
    id: '/$workoutId',
    path: '/$workoutId',
    getParentRoute: () => CoachLibraryWorkoutsRoute,
  } as any)
const CoachLibraryWorkoutsWorkoutIdIndexRoute =
  CoachLibraryWorkoutsWorkoutIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CoachLibraryWorkoutsWorkoutIdRoute,
  } as any)
const CoachProgramsProgramIdWorkoutsWorkoutIdRoute =
  CoachProgramsProgramIdWorkoutsWorkoutIdRouteImport.update({
    id: '/workouts/$workoutId',
    path: '/workouts/$workoutId',
    getParentRoute: () => CoachProgramsProgramIdRoute,
  } as any)
const CoachLibraryWorkoutsWorkoutIdPreviewRoute =
  CoachLibraryWorkoutsWorkoutIdPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => CoachLibraryWorkoutsWorkoutIdRoute,
  } as any)
const ClientProgramsProgramIdWorkoutsWorkoutIdRoute =
  ClientProgramsProgramIdWorkoutsWorkoutIdRouteImport.update({
    id: '/programs/$programId/workouts/$workoutId',
    path: '/programs/$programId/workouts/$workoutId',
    getParentRoute: () => ClientRoute,
  } as any)
const CoachProgramsProgramIdWorkoutsWorkoutIdIndexRoute =
  CoachProgramsProgramIdWorkoutsWorkoutIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CoachProgramsProgramIdWorkoutsWorkoutIdRoute,
  } as any)
const CoachProgramsProgramIdWorkoutsWorkoutIdPreviewRoute =
  CoachProgramsProgramIdWorkoutsWorkoutIdPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => CoachProgramsProgramIdWorkoutsWorkoutIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client': typeof ClientRouteWithChildren
  '/coach': typeof CoachRouteWithChildren
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/workout-history': typeof ClientWorkoutHistoryRoute
  '/coach/dashboard': typeof CoachDashboardRoute
  '/coach/exercises': typeof CoachExercisesRoute
  '/coach/library': typeof CoachLibraryRouteWithChildren
  '/coach/programs': typeof CoachProgramsRouteWithChildren
  '/coach/clients/$clientId': typeof CoachClientsClientIdRoute
  '/coach/library/exercises': typeof CoachLibraryExercisesRoute
  '/coach/library/workouts': typeof CoachLibraryWorkoutsRouteWithChildren
  '/coach/programs/$programId': typeof CoachProgramsProgramIdRouteWithChildren
  '/coach/library/': typeof CoachLibraryIndexRoute
  '/coach/programs/': typeof CoachProgramsIndexRoute
  '/coach/library/workouts/$workoutId': typeof CoachLibraryWorkoutsWorkoutIdRouteWithChildren
  '/coach/library/workouts/': typeof CoachLibraryWorkoutsIndexRoute
  '/coach/programs/$programId/': typeof CoachProgramsProgramIdIndexRoute
  '/client/programs/$programId/workouts/$workoutId': typeof ClientProgramsProgramIdWorkoutsWorkoutIdRoute
  '/coach/library/workouts/$workoutId/preview': typeof CoachLibraryWorkoutsWorkoutIdPreviewRoute
  '/coach/programs/$programId/workouts/$workoutId': typeof CoachProgramsProgramIdWorkoutsWorkoutIdRouteWithChildren
  '/coach/library/workouts/$workoutId/': typeof CoachLibraryWorkoutsWorkoutIdIndexRoute
  '/coach/programs/$programId/workouts/$workoutId/preview': typeof CoachProgramsProgramIdWorkoutsWorkoutIdPreviewRoute
  '/coach/programs/$programId/workouts/$workoutId/': typeof CoachProgramsProgramIdWorkoutsWorkoutIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/client': typeof ClientRouteWithChildren
  '/coach': typeof CoachRouteWithChildren
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/workout-history': typeof ClientWorkoutHistoryRoute
  '/coach/dashboard': typeof CoachDashboardRoute
  '/coach/exercises': typeof CoachExercisesRoute
  '/coach/clients/$clientId': typeof CoachClientsClientIdRoute
  '/coach/library/exercises': typeof CoachLibraryExercisesRoute
  '/coach/library': typeof CoachLibraryIndexRoute
  '/coach/programs': typeof CoachProgramsIndexRoute
  '/coach/library/workouts': typeof CoachLibraryWorkoutsIndexRoute
  '/coach/programs/$programId': typeof CoachProgramsProgramIdIndexRoute
  '/client/programs/$programId/workouts/$workoutId': typeof ClientProgramsProgramIdWorkoutsWorkoutIdRoute
  '/coach/library/workouts/$workoutId/preview': typeof CoachLibraryWorkoutsWorkoutIdPreviewRoute
  '/coach/library/workouts/$workoutId': typeof CoachLibraryWorkoutsWorkoutIdIndexRoute
  '/coach/programs/$programId/workouts/$workoutId/preview': typeof CoachProgramsProgramIdWorkoutsWorkoutIdPreviewRoute
  '/coach/programs/$programId/workouts/$workoutId': typeof CoachProgramsProgramIdWorkoutsWorkoutIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/client': typeof ClientRouteWithChildren
  '/coach': typeof CoachRouteWithChildren
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/workout-history': typeof ClientWorkoutHistoryRoute
  '/coach/dashboard': typeof CoachDashboardRoute
  '/coach/exercises': typeof CoachExercisesRoute
  '/coach/library': typeof CoachLibraryRouteWithChildren
  '/coach/programs': typeof CoachProgramsRouteWithChildren
  '/coach/clients/$clientId': typeof CoachClientsClientIdRoute
  '/coach/library/exercises': typeof CoachLibraryExercisesRoute
  '/coach/library/workouts': typeof CoachLibraryWorkoutsRouteWithChildren
  '/coach/programs/$programId': typeof CoachProgramsProgramIdRouteWithChildren
  '/coach/library/': typeof CoachLibraryIndexRoute
  '/coach/programs/': typeof CoachProgramsIndexRoute
  '/coach/library/workouts/$workoutId': typeof CoachLibraryWorkoutsWorkoutIdRouteWithChildren
  '/coach/library/workouts/': typeof CoachLibraryWorkoutsIndexRoute
  '/coach/programs/$programId/': typeof CoachProgramsProgramIdIndexRoute
  '/client/programs/$programId/workouts/$workoutId': typeof ClientProgramsProgramIdWorkoutsWorkoutIdRoute
  '/coach/library/workouts/$workoutId/preview': typeof CoachLibraryWorkoutsWorkoutIdPreviewRoute
  '/coach/programs/$programId/workouts/$workoutId': typeof CoachProgramsProgramIdWorkoutsWorkoutIdRouteWithChildren
  '/coach/library/workouts/$workoutId/': typeof CoachLibraryWorkoutsWorkoutIdIndexRoute
  '/coach/programs/$programId/workouts/$workoutId/preview': typeof CoachProgramsProgramIdWorkoutsWorkoutIdPreviewRoute
  '/coach/programs/$programId/workouts/$workoutId/': typeof CoachProgramsProgramIdWorkoutsWorkoutIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client'
    | '/coach'
    | '/client/dashboard'
    | '/client/workout-history'
    | '/coach/dashboard'
    | '/coach/exercises'
    | '/coach/library'
    | '/coach/programs'
    | '/coach/clients/$clientId'
    | '/coach/library/exercises'
    | '/coach/library/workouts'
    | '/coach/programs/$programId'
    | '/coach/library/'
    | '/coach/programs/'
    | '/coach/library/workouts/$workoutId'
    | '/coach/library/workouts/'
    | '/coach/programs/$programId/'
    | '/client/programs/$programId/workouts/$workoutId'
    | '/coach/library/workouts/$workoutId/preview'
    | '/coach/programs/$programId/workouts/$workoutId'
    | '/coach/library/workouts/$workoutId/'
    | '/coach/programs/$programId/workouts/$workoutId/preview'
    | '/coach/programs/$programId/workouts/$workoutId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/client'
    | '/coach'
    | '/client/dashboard'
    | '/client/workout-history'
    | '/coach/dashboard'
    | '/coach/exercises'
    | '/coach/clients/$clientId'
    | '/coach/library/exercises'
    | '/coach/library'
    | '/coach/programs'
    | '/coach/library/workouts'
    | '/coach/programs/$programId'
    | '/client/programs/$programId/workouts/$workoutId'
    | '/coach/library/workouts/$workoutId/preview'
    | '/coach/library/workouts/$workoutId'
    | '/coach/programs/$programId/workouts/$workoutId/preview'
    | '/coach/programs/$programId/workouts/$workoutId'
  id:
    | '__root__'
    | '/'
    | '/client'
    | '/coach'
    | '/client/dashboard'
    | '/client/workout-history'
    | '/coach/dashboard'
    | '/coach/exercises'
    | '/coach/library'
    | '/coach/programs'
    | '/coach/clients/$clientId'
    | '/coach/library/exercises'
    | '/coach/library/workouts'
    | '/coach/programs/$programId'
    | '/coach/library/'
    | '/coach/programs/'
    | '/coach/library/workouts/$workoutId'
    | '/coach/library/workouts/'
    | '/coach/programs/$programId/'
    | '/client/programs/$programId/workouts/$workoutId'
    | '/coach/library/workouts/$workoutId/preview'
    | '/coach/programs/$programId/workouts/$workoutId'
    | '/coach/library/workouts/$workoutId/'
    | '/coach/programs/$programId/workouts/$workoutId/preview'
    | '/coach/programs/$programId/workouts/$workoutId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientRoute: typeof ClientRouteWithChildren
  CoachRoute: typeof CoachRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/programs': {
      id: '/coach/programs'
      path: '/programs'
      fullPath: '/coach/programs'
      preLoaderRoute: typeof CoachProgramsRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/library': {
      id: '/coach/library'
      path: '/library'
      fullPath: '/coach/library'
      preLoaderRoute: typeof CoachLibraryRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/exercises': {
      id: '/coach/exercises'
      path: '/exercises'
      fullPath: '/coach/exercises'
      preLoaderRoute: typeof CoachExercisesRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/dashboard': {
      id: '/coach/dashboard'
      path: '/dashboard'
      fullPath: '/coach/dashboard'
      preLoaderRoute: typeof CoachDashboardRouteImport
      parentRoute: typeof CoachRoute
    }
    '/client/workout-history': {
      id: '/client/workout-history'
      path: '/workout-history'
      fullPath: '/client/workout-history'
      preLoaderRoute: typeof ClientWorkoutHistoryRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/dashboard': {
      id: '/client/dashboard'
      path: '/dashboard'
      fullPath: '/client/dashboard'
      preLoaderRoute: typeof ClientDashboardRouteImport
      parentRoute: typeof ClientRoute
    }
    '/coach/programs/': {
      id: '/coach/programs/'
      path: '/'
      fullPath: '/coach/programs/'
      preLoaderRoute: typeof CoachProgramsIndexRouteImport
      parentRoute: typeof CoachProgramsRoute
    }
    '/coach/library/': {
      id: '/coach/library/'
      path: '/'
      fullPath: '/coach/library/'
      preLoaderRoute: typeof CoachLibraryIndexRouteImport
      parentRoute: typeof CoachLibraryRoute
    }
    '/coach/programs/$programId': {
      id: '/coach/programs/$programId'
      path: '/$programId'
      fullPath: '/coach/programs/$programId'
      preLoaderRoute: typeof CoachProgramsProgramIdRouteImport
      parentRoute: typeof CoachProgramsRoute
    }
    '/coach/library/workouts': {
      id: '/coach/library/workouts'
      path: '/workouts'
      fullPath: '/coach/library/workouts'
      preLoaderRoute: typeof CoachLibraryWorkoutsRouteImport
      parentRoute: typeof CoachLibraryRoute
    }
    '/coach/library/exercises': {
      id: '/coach/library/exercises'
      path: '/exercises'
      fullPath: '/coach/library/exercises'
      preLoaderRoute: typeof CoachLibraryExercisesRouteImport
      parentRoute: typeof CoachLibraryRoute
    }
    '/coach/clients/$clientId': {
      id: '/coach/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/coach/clients/$clientId'
      preLoaderRoute: typeof CoachClientsClientIdRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/programs/$programId/': {
      id: '/coach/programs/$programId/'
      path: '/'
      fullPath: '/coach/programs/$programId/'
      preLoaderRoute: typeof CoachProgramsProgramIdIndexRouteImport
      parentRoute: typeof CoachProgramsProgramIdRoute
    }
    '/coach/library/workouts/': {
      id: '/coach/library/workouts/'
      path: '/'
      fullPath: '/coach/library/workouts/'
      preLoaderRoute: typeof CoachLibraryWorkoutsIndexRouteImport
      parentRoute: typeof CoachLibraryWorkoutsRoute
    }
    '/coach/library/workouts/$workoutId': {
      id: '/coach/library/workouts/$workoutId'
      path: '/$workoutId'
      fullPath: '/coach/library/workouts/$workoutId'
      preLoaderRoute: typeof CoachLibraryWorkoutsWorkoutIdRouteImport
      parentRoute: typeof CoachLibraryWorkoutsRoute
    }
    '/coach/library/workouts/$workoutId/': {
      id: '/coach/library/workouts/$workoutId/'
      path: '/'
      fullPath: '/coach/library/workouts/$workoutId/'
      preLoaderRoute: typeof CoachLibraryWorkoutsWorkoutIdIndexRouteImport
      parentRoute: typeof CoachLibraryWorkoutsWorkoutIdRoute
    }
    '/coach/programs/$programId/workouts/$workoutId': {
      id: '/coach/programs/$programId/workouts/$workoutId'
      path: '/workouts/$workoutId'
      fullPath: '/coach/programs/$programId/workouts/$workoutId'
      preLoaderRoute: typeof CoachProgramsProgramIdWorkoutsWorkoutIdRouteImport
      parentRoute: typeof CoachProgramsProgramIdRoute
    }
    '/coach/library/workouts/$workoutId/preview': {
      id: '/coach/library/workouts/$workoutId/preview'
      path: '/preview'
      fullPath: '/coach/library/workouts/$workoutId/preview'
      preLoaderRoute: typeof CoachLibraryWorkoutsWorkoutIdPreviewRouteImport
      parentRoute: typeof CoachLibraryWorkoutsWorkoutIdRoute
    }
    '/client/programs/$programId/workouts/$workoutId': {
      id: '/client/programs/$programId/workouts/$workoutId'
      path: '/programs/$programId/workouts/$workoutId'
      fullPath: '/client/programs/$programId/workouts/$workoutId'
      preLoaderRoute: typeof ClientProgramsProgramIdWorkoutsWorkoutIdRouteImport
      parentRoute: typeof ClientRoute
    }
    '/coach/programs/$programId/workouts/$workoutId/': {
      id: '/coach/programs/$programId/workouts/$workoutId/'
      path: '/'
      fullPath: '/coach/programs/$programId/workouts/$workoutId/'
      preLoaderRoute: typeof CoachProgramsProgramIdWorkoutsWorkoutIdIndexRouteImport
      parentRoute: typeof CoachProgramsProgramIdWorkoutsWorkoutIdRoute
    }
    '/coach/programs/$programId/workouts/$workoutId/preview': {
      id: '/coach/programs/$programId/workouts/$workoutId/preview'
      path: '/preview'
      fullPath: '/coach/programs/$programId/workouts/$workoutId/preview'
      preLoaderRoute: typeof CoachProgramsProgramIdWorkoutsWorkoutIdPreviewRouteImport
      parentRoute: typeof CoachProgramsProgramIdWorkoutsWorkoutIdRoute
    }
  }
}

interface ClientRouteChildren {
  ClientDashboardRoute: typeof ClientDashboardRoute
  ClientWorkoutHistoryRoute: typeof ClientWorkoutHistoryRoute
  ClientProgramsProgramIdWorkoutsWorkoutIdRoute: typeof ClientProgramsProgramIdWorkoutsWorkoutIdRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientDashboardRoute: ClientDashboardRoute,
  ClientWorkoutHistoryRoute: ClientWorkoutHistoryRoute,
  ClientProgramsProgramIdWorkoutsWorkoutIdRoute:
    ClientProgramsProgramIdWorkoutsWorkoutIdRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface CoachLibraryWorkoutsWorkoutIdRouteChildren {
  CoachLibraryWorkoutsWorkoutIdPreviewRoute: typeof CoachLibraryWorkoutsWorkoutIdPreviewRoute
  CoachLibraryWorkoutsWorkoutIdIndexRoute: typeof CoachLibraryWorkoutsWorkoutIdIndexRoute
}

const CoachLibraryWorkoutsWorkoutIdRouteChildren: CoachLibraryWorkoutsWorkoutIdRouteChildren =
  {
    CoachLibraryWorkoutsWorkoutIdPreviewRoute:
      CoachLibraryWorkoutsWorkoutIdPreviewRoute,
    CoachLibraryWorkoutsWorkoutIdIndexRoute:
      CoachLibraryWorkoutsWorkoutIdIndexRoute,
  }

const CoachLibraryWorkoutsWorkoutIdRouteWithChildren =
  CoachLibraryWorkoutsWorkoutIdRoute._addFileChildren(
    CoachLibraryWorkoutsWorkoutIdRouteChildren,
  )

interface CoachLibraryWorkoutsRouteChildren {
  CoachLibraryWorkoutsWorkoutIdRoute: typeof CoachLibraryWorkoutsWorkoutIdRouteWithChildren
  CoachLibraryWorkoutsIndexRoute: typeof CoachLibraryWorkoutsIndexRoute
}

const CoachLibraryWorkoutsRouteChildren: CoachLibraryWorkoutsRouteChildren = {
  CoachLibraryWorkoutsWorkoutIdRoute:
    CoachLibraryWorkoutsWorkoutIdRouteWithChildren,
  CoachLibraryWorkoutsIndexRoute: CoachLibraryWorkoutsIndexRoute,
}

const CoachLibraryWorkoutsRouteWithChildren =
  CoachLibraryWorkoutsRoute._addFileChildren(CoachLibraryWorkoutsRouteChildren)

interface CoachLibraryRouteChildren {
  CoachLibraryExercisesRoute: typeof CoachLibraryExercisesRoute
  CoachLibraryWorkoutsRoute: typeof CoachLibraryWorkoutsRouteWithChildren
  CoachLibraryIndexRoute: typeof CoachLibraryIndexRoute
}

const CoachLibraryRouteChildren: CoachLibraryRouteChildren = {
  CoachLibraryExercisesRoute: CoachLibraryExercisesRoute,
  CoachLibraryWorkoutsRoute: CoachLibraryWorkoutsRouteWithChildren,
  CoachLibraryIndexRoute: CoachLibraryIndexRoute,
}

const CoachLibraryRouteWithChildren = CoachLibraryRoute._addFileChildren(
  CoachLibraryRouteChildren,
)

interface CoachProgramsProgramIdWorkoutsWorkoutIdRouteChildren {
  CoachProgramsProgramIdWorkoutsWorkoutIdPreviewRoute: typeof CoachProgramsProgramIdWorkoutsWorkoutIdPreviewRoute
  CoachProgramsProgramIdWorkoutsWorkoutIdIndexRoute: typeof CoachProgramsProgramIdWorkoutsWorkoutIdIndexRoute
}

const CoachProgramsProgramIdWorkoutsWorkoutIdRouteChildren: CoachProgramsProgramIdWorkoutsWorkoutIdRouteChildren =
  {
    CoachProgramsProgramIdWorkoutsWorkoutIdPreviewRoute:
      CoachProgramsProgramIdWorkoutsWorkoutIdPreviewRoute,
    CoachProgramsProgramIdWorkoutsWorkoutIdIndexRoute:
      CoachProgramsProgramIdWorkoutsWorkoutIdIndexRoute,
  }

const CoachProgramsProgramIdWorkoutsWorkoutIdRouteWithChildren =
  CoachProgramsProgramIdWorkoutsWorkoutIdRoute._addFileChildren(
    CoachProgramsProgramIdWorkoutsWorkoutIdRouteChildren,
  )

interface CoachProgramsProgramIdRouteChildren {
  CoachProgramsProgramIdIndexRoute: typeof CoachProgramsProgramIdIndexRoute
  CoachProgramsProgramIdWorkoutsWorkoutIdRoute: typeof CoachProgramsProgramIdWorkoutsWorkoutIdRouteWithChildren
}

const CoachProgramsProgramIdRouteChildren: CoachProgramsProgramIdRouteChildren =
  {
    CoachProgramsProgramIdIndexRoute: CoachProgramsProgramIdIndexRoute,
    CoachProgramsProgramIdWorkoutsWorkoutIdRoute:
      CoachProgramsProgramIdWorkoutsWorkoutIdRouteWithChildren,
  }

const CoachProgramsProgramIdRouteWithChildren =
  CoachProgramsProgramIdRoute._addFileChildren(
    CoachProgramsProgramIdRouteChildren,
  )

interface CoachProgramsRouteChildren {
  CoachProgramsProgramIdRoute: typeof CoachProgramsProgramIdRouteWithChildren
  CoachProgramsIndexRoute: typeof CoachProgramsIndexRoute
}

const CoachProgramsRouteChildren: CoachProgramsRouteChildren = {
  CoachProgramsProgramIdRoute: CoachProgramsProgramIdRouteWithChildren,
  CoachProgramsIndexRoute: CoachProgramsIndexRoute,
}

const CoachProgramsRouteWithChildren = CoachProgramsRoute._addFileChildren(
  CoachProgramsRouteChildren,
)

interface CoachRouteChildren {
  CoachDashboardRoute: typeof CoachDashboardRoute
  CoachExercisesRoute: typeof CoachExercisesRoute
  CoachLibraryRoute: typeof CoachLibraryRouteWithChildren
  CoachProgramsRoute: typeof CoachProgramsRouteWithChildren
  CoachClientsClientIdRoute: typeof CoachClientsClientIdRoute
}

const CoachRouteChildren: CoachRouteChildren = {
  CoachDashboardRoute: CoachDashboardRoute,
  CoachExercisesRoute: CoachExercisesRoute,
  CoachLibraryRoute: CoachLibraryRouteWithChildren,
  CoachProgramsRoute: CoachProgramsRouteWithChildren,
  CoachClientsClientIdRoute: CoachClientsClientIdRoute,
}

const CoachRouteWithChildren = CoachRoute._addFileChildren(CoachRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientRoute: ClientRouteWithChildren,
  CoachRoute: CoachRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
